version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sensor_network

  springbootapp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springbootapp
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    networks:
      - sensor_network

networks:
  sensor_network:

volumes:
  mongodb_data:
    driver: local
